services:
  krishi-maitri-ui:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: krishi-maitri-ui
    ports:
      - "3000:80"
    restart: unless-stopped
    env_file:
      - /home/bhautikpithadiya12/krishi-mitri/frontend/.env
    environment:
      - NODE_ENV=production
    networks:
      - krishi-network

networks:
  krishi-network:
    driver: bridge
