version: '3.9'

services:
  krishi-maitri-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krishi-maitri-ui
    expose:
      - "3000"
    restart: unless-stopped
    env_file:
      - /home/bhautikpithadiya12/krishi-mitri/frontend/.env
    environment:
      - NODE_ENV=production
